# Site settings
title: Otro Nuzlocke mÃ¡s
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/Nuzlocke-16" # the subpath of your site, e.g. /blog/
url: "http://josemorval.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
